@startuml

package phongvan.hischoolbackend.Service {
    class StudentService {
        - studentRepository: StudentRepository
        - userRepository: UserRepository
        - schoolClassRepository: SchoolClassRepository
        - transcriptRepository: TranscriptRepository

        + aStudent(lastName: String): Student
        + allStudents(): List<Student>
        + findPaginated(schoolId: Integer, pageable: Pageable): Page<Student>
        + findPaginatedInClass(schoolClassId: Integer, pageable: Pageable): Page<Student>
        + deleteStudent(id: Integer): void
        + updateStudent(student: Student): void
        + existsByFirstName(lastName: String): boolean
        + findById(id: Integer): Student
        + removeStudentFromClass(schoolClassId: Integer, studentId: Integer): void
        + removeManyStudentsFromClass(schoolClassId: Integer, students: List<Integer>): void
        + addStudentFromClass(schoolClassId: Integer, studentId: Integer): void
        + addManyStudentsFromClass(schoolClassId: Integer, students: List<Integer>): void
        + findPaginatedNotInClass(schoolClassId: Integer, pageable: Pageable): Page<Student>
    }
}

@enduml
