@startuml

package phongvan.hischoolbackend.Service {
    @startuml
    class TeacherService {
        - teacherRepository: TeacherRepository
        - userRepository: UserRepository
        - timeTableDetailRepository: TimeTableDetailRepository

        + aTeacher(lastName: String): Teacher
        + allTeachers(): List<Teacher>
        + findPaginated(schoolId: Integer, pageable: Pageable): Page<Teacher>
        + deleteTeacher(id: Integer): void
        + updateTeacher(teacher: Teacher): void
        + existsByFirstName(lastName: String): boolean
        + findById(id: Integer): Teacher
        + findAllInSchool(schoolId: int): List<Teacher>
        + findAllInSchool_IdAndGroup(schoolId: int, group: String): List<Teacher>
        + findAllInSchool_IdAndGroup_Ready(schoolId: int, group: String): List<Teacher>
        + findAllInSchool_IdAndGroupAndSchedulesReady(schoolId: int, group: String, selectedSchedules: List<Integer>): List<Teacher>
        + hasScheduledTimeTableForWeekAndDay(teacher: Teacher, weeks: List<String>, days: List<String>, scheduleIds: List<Integer>): boolean
    }
    @enduml
}

@enduml
