@startuml

package phongvan.hischoolbackend.entity {
    class Address {
        - id: Integer
        - other: String
        - wardCommune: String
        - district: String
        - province: String
        - city: String

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<GeneratedValue>> IDENTITY
        {static} <<Override>> equals(o: Object): boolean
        {static} <<Override>> hashCode(): int

        + Address()
        + Address(id: Integer, other: String, wardCommune: String, district: String, province: String, city: String)
        + getId(): Integer
        + setId(id: Integer): void
        + getOther(): String
        + setOther(other: String): void
        + getWardCommune(): String
        + setWardCommune(wardCommune: String): void
        + getDistrict(): String
        + setDistrict(district: String): void
        + getProvince(): String
        + setProvince(province: String): void
        + getCity(): String
        + setCity(city: String): void
    }
}

@enduml
