@startuml

package phongvan.hischoolbackend.entity {
    class IssuedPlace {
        - id: Integer
        - name: String
        - address: Address

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<OneToOne>> address
        {static} <<Override>> toString(): String

        + IssuedPlace()
        + IssuedPlace(id: Integer, name: String, address: Address)
        + getId(): Integer
        + setId(id: Integer): void
        + getName(): String
        + setName(name: String): void
        + getAddress(): Address
        + setAddress(address: Address): void
    }
}

@enduml
