@startuml

package phongvan.hischoolbackend.entity {
    class Parent {
        - id: Integer
        - firstName: String
        - lastName: String
        - students: List<Student>

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<OneToMany>> students
        {static} <<JsonIgnore>> students

        + Parent()
        + Parent(id: Integer, firstName: String, lastName: String, students: List<Student>)
        + getId(): Integer
        + setId(id: Integer): void
        + getFirstName(): String
        + setFirstName(firstName: String): void
        + getLastName(): String
        + setLastName(lastName: String): void
        + getStudents(): List<Student>
        + setStudents(students: List<Student>): void
        + toString(): String
    }
}

@enduml
