@startuml

package phongvan.hischoolbackend.entity {
    class SchoolYear {
        - id: Integer
        - name: String
        - school: School
        - semesters: List<Semester>

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<ManyToOne>> school
        {static} <<JsonManagedReference>> school
        {static} <<OneToMany>> semesters
        {static} <<JsonIgnore>> semesters

        + SchoolYear()
        + SchoolYear(id: Integer, name: String, school: School, semesters: List<Semester>)
        + getId(): Integer
        + setId(id: Integer): void
        + getName(): String
        + setName(name: String): void
        + getSchool(): School
        + setSchool(school: School): void
        + getSemesters(): List<Semester>
        + setSemesters(semesters: List<Semester>): void
        + toString(): String
    }
}

@enduml
