@startuml

package phongvan.hischoolbackend.entity {
    class School {
        - id: Integer
        - name: String
        - address: Address
        - schoolYears: List<SchoolYear>

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<OneToOne>> address
        {static} <<OneToMany>> schoolYears
        {static} <<JsonIgnore>> schoolYears

        + School()
        + School(id: Integer, name: String, address: Address, schoolYears: List<SchoolYear>)
        + getId(): Integer
        + setId(id: Integer): void
        + getName(): String
        + setName(name: String): void
        + getAddress(): Address
        + setAddress(address: Address): void
        + getSchoolYears(): List<SchoolYear>
        + setSchoolYears(schoolYears: List<SchoolYear>): void
        + toString(): String
    }
}

@enduml
