@startuml

package phongvan.hischoolbackend.entity {
    class Score {
        - id: Integer
        - subject: Subject
        - student: Student
        - semester: Semester
        - teacher: Teacher
        - dailyScore: Double
        - midtermScore: Double
        - finalScore: Double
        - subjectScore: Double
        - subjectEvaluation: String

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<ManyToOne>> subject
        {static} <<JsonManagedReference>> subject
        {static} <<ManyToOne>> student
        {static} <<JsonManagedReference>> student
        {static} <<ManyToOne>> semester
        {static} <<JsonManagedReference>> semester
        {static} <<ManyToOne>> teacher
        {static} <<JsonManagedReference>> teacher

        + Score()
        + Score(id: Integer, subject: Subject, student: Student, semester: Semester, teacher: Teacher, dailyScore: Double, midtermScore: Double, finalScore: Double, subjectScore: Double, subjectEvaluation: String)
        + getId(): Integer
        + setId(id: Integer): void
        + getSubject(): Subject
        + setSubject(subject: Subject): void
        + getStudent(): Student
        + setStudent(student: Student): void
        + getSemester(): Semester
        + setSemester(semester: Semester): void
        + getTeacher(): Teacher
        + setTeacher(teacher: Teacher): void
        + getDailyScore(): Double
        + setDailyScore(dailyScore: Double): void
        + getMidtermScore(): Double
        + setMidtermScore(midtermScore: Double): void
        + getFinalScore(): Double
        + setFinalScore(finalScore: Double): void
        + getSubjectScore(): Double
        + setSubjectScore(subjectScore: Double): void
        + getSubjectEvaluation(): String
        + setSubjectEvaluation(subjectEvaluation: String): void
        + toString(): String
    }
}

@enduml
