@startuml

package phongvan.hischoolbackend.entity {
    class Student {
        - id: Integer
        - user: User
        - parent: Parent
        - transcripts: Collection<Transcript>
        - avatar: String
        - firstName: String
        - lastName: String
        - dateOfBirth: String
        - nationality: String
        - ethnicity: String
        - citizenId: String
        - issuedDate: String
        - issuedPlace: IssuedPlace
        - permanentAddress: Address
        - contactAddress: Address
        - classes: Collection<SchoolClass>
        - scores: Collection<Score>

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<OneToOne>> user
        {static} <<ManyToOne>> parent
        {static} <<OneToMany>> transcripts
        {static} <<Lob>> avatar
        {static} <<ManyToOne>> issuedPlace
        {static} <<ManyToOne>> permanentAddress
        {static} <<ManyToOne>> contactAddress
        {static} <<ManyToMany>> classes
        {static} <<OneToMany>> scores
        {static} <<JsonIgnore>> transcripts
        {static} <<JsonIgnore>> classes

        + Student()
        + Student(id: Integer, user: User, parent: Parent, transcripts: Collection<Transcript>, avatar: String, firstName: String, lastName: String, dateOfBirth: String, nationality: String, ethnicity: String, citizenId: String, issuedDate: String, issuedPlace: IssuedPlace, permanentAddress: Address, contactAddress: Address, classes: Collection<SchoolClass>, scores: Collection<Score>)
        + getId(): Integer
        + setId(id: Integer): void
        + getUser(): User
        + setUser(user: User): void
        + getParent(): Parent
        + setParent(parent: Parent): void
        + getTranscripts(): Collection<Transcript>
        + setTranscripts(transcripts: Collection<Transcript>): void
        + getAvatar(): String
        + setAvatar(avatar: String): void
        + getFirstName(): String
        + setFirstName(firstName: String): void
        + getLastName(): String
        + setLastName(lastName: String): void
        + getDateOfBirth(): String
        + setDateOfBirth(dateOfBirth: String): void
        + getNationality(): String
        + setNationality(nationality: String): void
        + getEthnicity(): String
        + setEthnicity(ethnicity: String): void
        + getCitizenId(): String
        + setCitizenId(citizenId: String): void
        + getIssuedDate(): String
        + setIssuedDate(issuedDate: String): void
        + getIssuedPlace(): IssuedPlace
        + setIssuedPlace(issuedPlace: IssuedPlace): void
        + getPermanentAddress(): Address
        + setPermanentAddress(permanentAddress: Address): void
        + getContactAddress(): Address
        + setContactAddress(contactAddress: Address): void
        + getClasses(): Collection<SchoolClass>
        + setClasses(classes: Collection<SchoolClass>): void
        + getScores(): Collection<Score>
        + setScores(scores: Collection<Score>): void
        + toString(): String
    }
}

@enduml
