@startuml

package phongvan.hischoolbackend.entity {
    class Subject {
        - id: Integer
        - name: String
        - grade: String
        - semester: Semester
        - scores: Set<Score>

        {static} <<ID>> id
        {static} <<GeneratedValue>> strategy
        {static} <<ManyToOne>> semester
        {static} <<OneToMany>> scores

        + Subject()
        + Subject(id: Integer, name: String, grade: String, semester: Semester, scores: Set<Score>)
        + getId(): Integer
        + setId(id: Integer): void
        + getName(): String
        + setName(name: String): void
        + getGrade(): String
        + setGrade(grade: String): void
        + getSemester(): Semester
        + setSemester(semester: Semester): void
        + getScores(): Set<Score>
        + setScores(scores: Set<Score>): void
        + toString(): String
    }
}

@enduml
