@startuml

package phongvan.hischoolbackend.entity {
    class Teacher {
        - id: Integer
        - user: User
        - avatar: String
        - firstName: String
        - lastName: String
        - dateOfBirth: String
        - nationality: String
        - ethnicity: String
        - citizenId: String
        - issuedDate: String
        - issuedPlace: IssuedPlace
        - permanentAddress: Address
        - contactAddress: Address
        - firstWorkDate: String
        - group: String
        - timeTableDetails: Set<TimeTableDetail>

        {static} <<ID>> id
        {static} <<OneToOne>> user
        {static} <<Lob>> avatar
        {static} <<ManyToOne>> issuedPlace
        {static} <<JsonManagedReference>> issuedPlace
        {static} <<ManyToOne>> permanentAddress
        {static} <<JsonManagedReference>> permanentAddress
        {static} <<ManyToOne>> contactAddress
        {static} <<JsonManagedReference>> contactAddress
        {static} <<OneToMany>> timeTableDetails
        {static} <<JsonBackReference>> timeTableDetails

        + Teacher()
        + Teacher(id: Integer, user: User, avatar: String, firstName: String, lastName: String, dateOfBirth: String, nationality: String, ethnicity: String, citizenId: String, issuedDate: String, issuedPlace: IssuedPlace, permanentAddress: Address, contactAddress: Address, firstWorkDate: String, group: String, timeTableDetails: Set<TimeTableDetail>)
        + getId(): Integer
        + setId(id: Integer): void
        + getUser(): User
        + setUser(user: User): void
        + getAvatar(): String
        + setAvatar(avatar: String): void
        + getFirstName(): String
        + setFirstName(firstName: String): void
        + getLastName(): String
        + setLastName(lastName: String): void
        + getDateOfBirth(): String
        + setDateOfBirth(dateOfBirth: String): void
        + getNationality(): String
        + setNationality(nationality: String): void
        + getEthnicity(): String
        + setEthnicity(ethnicity: String): void
        + getCitizenId(): String
        + setCitizenId(citizenId: String): void
        + getIssuedDate(): String
        + setIssuedDate(issuedDate: String): void
        + getIssuedPlace(): IssuedPlace
        + setIssuedPlace(issuedPlace: IssuedPlace): void
        + getPermanentAddress(): Address
        + setPermanentAddress(permanentAddress: Address): void
        + getContactAddress(): Address
        + setContactAddress(contactAddress: Address): void
        + getFirstWorkDate(): String
        + setFirstWorkDate(firstWorkDate: String): void
        + getGroup(): String
        + setGroup(group: String): void
        + getTimeTableDetails(): Set<TimeTableDetail>
        + setTimeTableDetails(timeTableDetails: Set<TimeTableDetail>): void
        + toString(): String
        + equals(o: Object): boolean
        + hashCode(): int
    }
}

@enduml
