@startuml

package phongvan.hischoolbackend.entity {
    class TimeTable {
        - id: Integer
        - studyDay: String
        - studyDate: String
        - studyWeek: String
        - semester: Semester

        {static} <<ID>> id
        {static} <<ManyToOne>> semester
        {static} <<JsonManagedReference>> semester

        + TimeTable()
        + TimeTable(id: Integer, studyDay: String, studyDate: String, studyWeek: String, semester: Semester)
        + getId(): Integer
        + setId(id: Integer): void
        + getStudyDay(): String
        + setStudyDay(studyDay: String): void
        + getStudyDate(): String
        + setStudyDate(studyDate: String): void
        + getStudyWeek(): String
        + setStudyWeek(studyWeek: String): void
        + getSemester(): Semester
        + setSemester(semester: Semester): void
        + toString(): String
    }
}

@enduml
