@startuml

package phongvan.hischoolbackend.entity {
    class TimeTableDetail {
        - id: Integer
        - timeTable: TimeTable
        - teacher: Teacher
        - schoolClass: SchoolClass
        - schedule: Schedule
        - subject: Subject
        - classComment: String

        {static} <<ID>> id
        {static} <<ManyToOne>> timeTable
        {static} <<JsonManagedReference>> timeTable
        {static} <<ManyToOne>> teacher
        {static} <<JsonManagedReference>> teacher
        {static} <<ManyToOne>> schoolClass
        {static} <<JsonManagedReference>> schoolClass
        {static} <<ManyToOne>> schedule
        {static} <<JsonManagedReference>> schedule
        {static} <<ManyToOne>> subject

        + TimeTableDetail()
        + TimeTableDetail(id: Integer, timeTable: TimeTable, teacher: Teacher, schoolClass: SchoolClass, schedule: Schedule, subject: Subject, classComment: String)
        + getId(): Integer
        + setId(id: Integer): void
        + getTimeTable(): TimeTable
        + setTimeTable(timeTable: TimeTable): void
        + getTeacher(): Teacher
        + setTeacher(teacher: Teacher): void
        + getSchoolClass(): SchoolClass
        + setSchoolClass(schoolClass: SchoolClass): void
        + getSchedule(): Schedule
        + setSchedule(schedule: Schedule): void
        + getSubject(): Subject
        + setSubject(subject: Subject): void
        + getClassComment(): String
        + setClassComment(classComment: String): void
    }
}

@enduml
