@startuml

package phongvan.hischoolbackend.Controller {
    class RoleController {
        - roleService: RoleService

        + getAllRole(): ResponseEntity<MessageResponse>
        + getAllRoleForAdmin(): ResponseEntity<MessageResponse>
        + getAllRoleForManager(): ResponseEntity<MessageResponse>
    }
}

@enduml
