@startuml

package phongvan.hischoolbackend.Controller {
    class ScheduleController {
        - scheduleService: ScheduleService
        - semesterRepository: SemesterRepository

        + getScheduleWithPagination(page: int, limit: int, schoolId: int): ResponseEntity<MessageResponse>
        + getSchedulesWithSemesterId(semesterId: int): ResponseEntity<MessageResponse>
        + checkExistSchedule(scheduleName: String, semesterId: Integer): boolean
        + addSchedule(scheduleRequest: ScheduleRequest): ResponseEntity<?>
        + deleteSchedule(id: int): ResponseEntity<MessageResponse>
        + updateSchedule(scheduleRequest: ScheduleRequest): ResponseEntity<?>
    }
}

@enduml
