@startuml

package phongvan.hischoolbackend.Controller {
    class ScoreController {
        - scoreService: ScoreService
        - notificationRepository: NotificationRepository

        + getScoreWithPagination(page: int, limit: int, semesterId: int, studentId: int): ResponseEntity<MessageResponse>
        + getScoreForTeacherWithPagination(page: int, limit: int, semesterId: int, studentId: int, username: String): ResponseEntity<MessageResponse>
        + getSemesterEvaluation(semesterId: int, studentId: int): ResponseEntity<MessageResponse>
        + UpdateTranscript(scoreRequest: ScoreRequest): ResponseEntity<?>
    }
}

@enduml
