@startuml

package phongvan.hischoolbackend.Controller {
    class SubjectController {
        - subjectService: SubjectService
        - semesterRepository: SemesterRepository

        + getAllSubjectName(): String[]
        + getAllSubjectBySemester(semesterId: int): ResponseEntity<MessageResponse>
        + getSchoolClassWithGradeAndYearId(grade: String, semesterId: int): ResponseEntity<MessageResponse>
        + getSubjectWithPagination(page: int, limit: int, schoolId: int): ResponseEntity<MessageResponse>
        + checkExistSubject(subjectName: String, semesterId: Integer): boolean
        + addSubject(subjectRequest: SubjectRequest): ResponseEntity<?>
        + deleteSubject(id: int): ResponseEntity<MessageResponse>
        + updateSubject(subjectRequest: SubjectRequest): ResponseEntity<MessageResponse>
    }
}

@enduml
