@startuml

package phongvan.hischoolbackend.Controller {
    class TeacherController {
        - teacherService: TeacherService
        - addressRepository: AddressRepository
        - issuedPlaceRepository: IssuedPlaceRepository
        - parentRepository: ParentRepository
        - userRepository: UserRepository
        - roleRepository: RoleRepository
        - schoolRepository: SchoolRepository
        - classRepository: SchoolClassRepository
        - encoder: PasswordEncoder

        + getAllGroupName(): String[]
        + getAllTeachersInSchool(schoolId: int): ResponseEntity<MessageResponse>
        + getATeacherWithClass(classId: int): ResponseEntity<MessageResponse>
        + getAllTeachersWithGroupInSchool(schoolId: int, group: String): ResponseEntity<MessageResponse>
        + getAllTeachersWithGroupInSchoolReady(schoolId: int, group: String, selectedSchedules: List<Integer>, selectedWeeks: List<String>, selectedDays: List<String>): ResponseEntity<MessageResponse>
        + getSchoolWithPagination(page: int, limit: int, schoolId: int): ResponseEntity<MessageResponse>
        + addTeacher(teacherRequest: TeacherRequest): ResponseEntity<?>
        + deleteTeacher(id: int): ResponseEntity<MessageResponse>
        + updateTeacher(teacherRequest: TeacherRequest): ResponseEntity<?>
    }
}

@enduml
