@startuml

package phongvan.hischoolbackend.Controller {
    class UserController {
        - userService: UserService
        - roleRepository: RoleRepository
        - schoolRepository: SchoolRepository
        - notificationRepository: NotificationRepository

        + getUserWithPagination(page: int, limit: int): ResponseEntity<MessageResponse>
        + getUserDetail(username: String): ResponseEntity<MessageResponse>
        + countNumberNotificationsUnRead(username: String): ResponseEntity<MessageResponse>
        + getAllNotificationsByUsernamePagination(page: int, limit: int, username: String): ResponseEntity<MessageResponse>
        + getUsersWithManagerRole(page: int, limit: int): ResponseEntity<MessageResponse>
        + getUsersWithoutManagerAndAdmin(page: int, limit: int, schoolId: Integer): ResponseEntity<MessageResponse>
        + deleteUser(id: int): ResponseEntity<MessageResponse>
        + changeUserPassword(request: Map<String, String>): ResponseEntity<MessageResponse>
        + updateUser(userRequest: UserRequest): ResponseEntity<MessageResponse>
        + changeStatus(id: int): ResponseEntity<MessageResponse>
    }
}

@enduml
