@startuml

package phongvan.hischoolbackend.Controller {
    class YearController {
        - yearService: YearService
        - schoolRepository: SchoolRepository

        + getAllYears(): ResponseEntity<MessageResponse>
        + getAllYearsInSchool(schoolId: int): ResponseEntity<MessageResponse>
        + getYearInSchoolWithPagination(page: int, limit: int, schoolId: int): ResponseEntity<MessageResponse>
        + addYear(yearRequest: YearRequest): ResponseEntity<?>
        + deleteYear(id: int): ResponseEntity<MessageResponse>
        + updateYear(yearRequest: YearRequest): ResponseEntity<MessageResponse>
    }
}

@enduml
