@startuml

(*) --> "Receive a request to find a user by username"

if "Request: anUser" then
    --> "Search for the user by username"
    --> if "Found user" then
        --> "Return the user"
        --> (*)
    else
        --> "Return null (user not found)"
        --> (*)
    endif
else
    --> "Invalid request"
    --> "Return null (user not found)"
    --> (*)
endif

@enduml
