@startuml

(*) --> "Receive a request to update a user's information"

if "Request: updateUser" then
    --> "Update the user's information in the database"
    --> "Return success message"
    --> (*)
else
    --> "Invalid request"
    --> "Return error message"
    --> (*)
endif

@enduml
